[#175476527] release pipeline
pagopa/io-developer-portal-frontend pull request #152
Opened 2020-12-02 16:41 UTC by balanza

Same changes applied in https://github.com/pagopa/io-functions-services/pull/96.

### Changes in brief
* Introduce the `Release` stage on the pipeline which marks a release on the repository
* Refactor the whole CI/CD to have 
  * separated pipelines for code review and deploy scenarios
  * everything is into `.devops` folder now

2020-12-02 16:48 UTC, balanza commented
/azp run

2020-12-03 07:33 UTC, balanza commented
Wait for https://github.com/pagopa/io-developer-portal-frontend/pull/153 to close

2020-12-03 08:30 UTC, balanza commented
/azp run

2020-12-03 11:57 UTC, pasqualedevita requested changes

2020-12-03 11:57 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +      ref: refs/tags/v3
```suggestion
      ref: refs/tags/v4
```

2020-12-03 15:26 UTC, merged

2020-12-03 16:47 UTC, balanza commented
/azp run pagopa.io-developer-portal-frontend.deploy

2020-12-03 16:47 UTC, balanza commented
/azp run